import s from "./../../styles/FoundBeer.module.scss";

import React, {useEffect, useState} from "react";
import {useRouter} from "next/router";
import Head from "next/head";

import {Header} from "../../components/Header/Header";
import {getOneBeer} from "../../core/api/api";
import {BeerList} from "../../core/interfaces/beerList";
import {BeerPost} from "../../components/BeerPost/BeerPost";
import {Preloader} from "../../components/Preloader/Preloader";


export default function FoundBeer() {

    const {query} = useRouter();
    const [beer, setBeer] = useState<[BeerList] | []>([]);
    const [loading, setLoading] = useState<boolean>(false);
    const [error, setError] = useState<boolean>(false);

    useEffect(() => {
        if (query.id) {
            getOneBeer(query.id)
                .then(result => {
                    setBeer(result.data);
                    setLoading(true);
                })
                .catch(e => setError(true));
        }
    }, []);

    return (
        <div className={s.container}>
            <Head>
                <title>Beer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/beer/favicon.ico"/>
            </Head>

            <header>
                <Header type={"id"}/>
            </header>

            <main className={s.main}>
                {loading && !error && beer.map(item => (
                    <BeerPost image_url={item.image_url} name={item.name} tagline={item.tagline} abv={item.abv}
                              description={item.description} food_pairing={item.food_pairing}/>
                ))}
                {!loading && !error && < Preloader/>}
                {error && <div className={s.not_found}><h2>Sorry, something went wrong...</h2></div>}
            </main>
        </div>
    )
};